name: ruta_generator
description: Generator for ruta framework
version: 0.1.8
repository: https://github.com/k0zlov/ruta_generator

environment:
  sdk: ^3.9.2

dependencies:
  ruta: ^0.1.20
  build: ^2.4.1
  collection: ^1.19.1
  glob: ^2.1.3
  shelf_swagger_ui: ^2.0.0
  analyzer: ^7.7.1
  get_it: ^8.0.3
  injectable: ^2.5.0

dev_dependencies:
  very_good_analysis: ^5.1.0
  test: ^1.24.0
  build_runner: ^2.4.13
